name:  Sowar2
author:  dirarko
current:  1
category:  Widgets
sources: ["Source/Sowar2.js"]
tags:  [image,carousel,animation,slideshow,slider]
demo:  http://www.developer.ps/moo/Sowar2
docs:  http://www.developer.ps/moo/Sowar2